networks:
  dev:

services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
     - '3000:3000'
  
  django:
    build:
      context: ./django
    ports:
      - "8000:8000"
    networks:
      - dev

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - django
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    networks:
      - dev
    environment:
      - SERVER_NAME=127.0.0.1
  